// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ItManagement
{

    // Genereret af EF
    public partial class Accesory
    {
        public int Tid { get; set; }
        public bool IsBorrowed { get; set; }
        public string Type { get; set; }
    }
}