// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ItManagement
{

    // Genereret af EF
    public partial class Computer
    {
        private int _uid;
        private bool _isBorrowed;
        public Computer(int uid)
        {
            Uid = uid;
            _isBorrowed = false;
        }

        public Computer()
        {
            IsBorrowed = false;
        }
        public int Uid { get; set; }
        public bool IsBorrowed { get; set; }

        public virtual Equipment U { get; set; }
    }
}