// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Xml;

namespace ItManagement
{
    // Genereret af EF
    public partial class Error
    {
        #region Instance Field
        private int _cpr;
        private int _uid;
        private string _errorMessage;
        private DateTime _create;
        private DateTime _update;
        private bool _isRepaired;
        private int _hasRepaired;
        #endregion

        #region Constructor


        public Error(int cpr, int uid, string errorMessage, bool isRepaired, int hasRepaired)
        {
            _cpr = cpr;
            _uid = uid;
            _errorMessage = errorMessage;
            _create = DateTime.Now;
            _update = DateTime.Now;
            _isRepaired = isRepaired;
            _hasRepaired = hasRepaired;



        }
        #endregion

        #region Properties
        public int Fid { get; set; }

        public int Cpr
        {
            get { return _cpr; }
            set { _cpr = value; }
        }
        public int Uid
        {
            get { return _uid; }
            set { _uid = value; }
            
        }


        public string ErrorMessage
        {
            get { return _errorMessage; }
            set { _errorMessage = value; }
        }
    
        public DateTime Create
        {
             get { return _create; }
             set { _create = value; }
        }

        public DateTime Update
        {
            get { return _update; }
            set { _update = value; }
        }

        public bool IsRepaired
        {
            get { return _isRepaired; }
            set { _isRepaired = value; }
        }

        public int HasRepaired
        {
            get { return _hasRepaired; }
            set { _hasRepaired = value; }
        }

        public string HasRepairedString
        {
            get
            {
                if (HasRepaired == 1234567891)
                {
                    return "None";
                }
                else
                {
                    return HasRepaired.ToString();
                }
            }
        }


        public string IsRepairedString
        {
            get { return IsRepaired.ToString(); }
        }
        public virtual Employee CprNavigation { get; set; }
        public virtual Equipment U { get; set; }
    }
    #endregion
}