// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ItManagement
{
    
    public partial class SmartBoard
    {
        private int _uid;
        private int _roomID;
        public SmartBoard(int uid)
        {
            Uid = uid;
            _roomID = 0;
        }

        public SmartBoard()
        {
            _roomID = 0;
        }

        public SmartBoard(int uid, int roomid)
        {
            _uid = uid;
            _roomID = roomid;
        }

        public int Uid { get; set; }

        public int Roomid
        {
            get { return _roomID; }
            set { _roomID = value; }
        }

        public virtual Equipment U { get; set; }
    }
}